<a href="https://colab.research.google.com/github/junsookim76/Ewha_2025/blob/main/2_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

> Import "numpy"
>
> The fundamental package for scientific computing with Python


In [1]:
import numpy as np

import matplotlib.pyplot as plt
import sys,os,copy,random,math
%matplotlib inline

## **1. Introducing numpy array**

In [2]:
array=[1,2,3,4,5,6,7,8]

print(array)
print(type(array))
print(len(array))

numpy_array=np.array(array)
print(type(numpy_array))
print(numpy_array)
print(numpy_array.dtype)
print(numpy_array.shape)

[1, 2, 3, 4, 5, 6, 7, 8]
<class 'list'>
8
<class 'numpy.ndarray'>
[1 2 3 4 5 6 7 8]
int64
(8,)


In [3]:
array2=2*array

print(array)
print(array2)

numpy_array2=2*numpy_array
print(numpy_array)
print(numpy_array2)


[1, 2, 3, 4, 5, 6, 7, 8]
[1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8]
[1 2 3 4 5 6 7 8]
[ 2  4  6  8 10 12 14 16]


In [4]:
numpy_array3=np.array([1,2,3,4,5,6,7,8])
print(type(numpy_array3))
print(numpy_array3)
print(numpy_array3.dtype)
print(numpy_array3.shape)


<class 'numpy.ndarray'>
[1 2 3 4 5 6 7 8]
int64
(8,)


In [5]:
numpy_array4=np.arange(1,9)
print(type(numpy_array4))
print(numpy_array4)
print(numpy_array4.dtype)
print(numpy_array4.shape)


<class 'numpy.ndarray'>
[1 2 3 4 5 6 7 8]
int64
(8,)


## **2. Change array shape**

In [6]:
new_array=np.reshape(array,(2,4))
print(new_array)
print(new_array.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [7]:
new_array=np.reshape(array,(2,-1))
print(new_array)

[[1 2 3 4]
 [5 6 7 8]]


## **3.Indexing and slicing**

In [8]:
print(new_array[1,2])
print(new_array[1][2])

7
7


In [9]:
new_array[1,:]

array([5, 6, 7, 8])

In [10]:
new_array[0,::2]

array([1, 3])

In [11]:
new_array[0,1::2]

array([2, 4])

In [12]:
array2=new_array[:,:2]
array2

array([[1, 2],
       [5, 6]])

In [13]:
new2=np.zeros((8,8))
new2

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [14]:
new2[2::3,4::2]=array2
new2

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 2., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 5., 0., 6., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [15]:
print(new_array)
new_array>2

[[1 2 3 4]
 [5 6 7 8]]


array([[False, False,  True,  True],
       [ True,  True,  True,  True]])

In [16]:
new_array[new_array>2]

array([3, 4, 5, 6, 7, 8])

## **4.Calculation**

In [27]:
print(new_array)
print(new_array.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [18]:
new_array+2

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [19]:
new_array/new_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.sum(new_array,axis=0)

array([ 6,  8, 10, 12])

In [21]:
np.sum(new_array,axis=1)

array([10, 26])

In [24]:
np.mean(new_array,axis=0)

array([3., 4., 5., 6.])

In [25]:
np.mean(new_array,axis=1)

array([2.5, 6.5])

In [22]:
new_array[0]

array([1, 2, 3, 4])

In [23]:
np.dot(new_array[0],new_array[1])

np.int64(70)

## **5. Input & Output**

In [ ]:
np.savetxt("data.txt",new_array)

In [ ]:
array=np.loadtxt("data.txt")
array

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [ ]:
print(array[0])
print(array[:,1])

[1. 2. 3. 4.]
[2. 6.]


## **6. Math Functions and Symbols**

In [ ]:
np.pi

3.141592653589793

In [ ]:
theta=np.arange(0,2*np.pi,np.pi/10)
print(type(theta))
print(theta)
print(theta.shape)

<class 'numpy.ndarray'>
[0.         0.31415927 0.62831853 0.9424778  1.25663706 1.57079633
 1.88495559 2.19911486 2.51327412 2.82743339 3.14159265 3.45575192
 3.76991118 4.08407045 4.39822972 4.71238898 5.02654825 5.34070751
 5.65486678 5.96902604]
20
(20,)


In [ ]:
np.sin(theta)

array([ 0.00000000e+00,  3.09016994e-01,  5.87785252e-01,  8.09016994e-01,
        9.51056516e-01,  1.00000000e+00,  9.51056516e-01,  8.09016994e-01,
        5.87785252e-01,  3.09016994e-01,  1.22464680e-16, -3.09016994e-01,
       -5.87785252e-01, -8.09016994e-01, -9.51056516e-01, -1.00000000e+00,
       -9.51056516e-01, -8.09016994e-01, -5.87785252e-01, -3.09016994e-01])

# Exercise 1. 학생들의 성적 처리하기

> 철수: 수학 70점, 국어 82점, 영어 91점, 과학 87점
>
> 영희: 수학 97점, 국어 80점, 영어 92점, 과학 80점
>
> 재규: 수학 43점, 국어 99점, 영어 100점, 과학 60점
>
> 은지: 수학 100점, 국어 93점, 영어 94점, 과학 97점

학생들의 성적을 record라는 numpy array에 입력하고 **(1) 개인별 평균과 표준편차**, **(2) 과목별 평균과 표준편차**를 계산하시오
